// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package enum

import (
	"errors"
	"fmt"
)

const (
	// DeviceTypeUnknown is a DeviceType of type Unknown.
	DeviceTypeUnknown DeviceType = iota
	// DeviceTypeWeb is a DeviceType of type Web.
	DeviceTypeWeb
	// DeviceTypeApi is a DeviceType of type Api.
	DeviceTypeApi
	// DeviceTypeDesktop is a DeviceType of type Desktop.
	DeviceTypeDesktop
	// DeviceTypeMobile is a DeviceType of type Mobile.
	DeviceTypeMobile
	// DeviceTypeChromeExtension is a DeviceType of type Chrome_extension.
	DeviceTypeChromeExtension
)

var ErrInvalidDeviceType = errors.New("not a valid DeviceType")

const _DeviceTypeName = "unknownwebapidesktopmobilechrome_extension"

var _DeviceTypeMap = map[DeviceType]string{
	DeviceTypeUnknown:         _DeviceTypeName[0:7],
	DeviceTypeWeb:             _DeviceTypeName[7:10],
	DeviceTypeApi:             _DeviceTypeName[10:13],
	DeviceTypeDesktop:         _DeviceTypeName[13:20],
	DeviceTypeMobile:          _DeviceTypeName[20:26],
	DeviceTypeChromeExtension: _DeviceTypeName[26:42],
}

// String implements the Stringer interface.
func (x DeviceType) String() string {
	if str, ok := _DeviceTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("DeviceType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DeviceType) IsValid() bool {
	_, ok := _DeviceTypeMap[x]
	return ok
}

var _DeviceTypeValue = map[string]DeviceType{
	_DeviceTypeName[0:7]:   DeviceTypeUnknown,
	_DeviceTypeName[7:10]:  DeviceTypeWeb,
	_DeviceTypeName[10:13]: DeviceTypeApi,
	_DeviceTypeName[13:20]: DeviceTypeDesktop,
	_DeviceTypeName[20:26]: DeviceTypeMobile,
	_DeviceTypeName[26:42]: DeviceTypeChromeExtension,
}

// ParseDeviceType attempts to convert a string to a DeviceType.
func ParseDeviceType(name string) (DeviceType, error) {
	if x, ok := _DeviceTypeValue[name]; ok {
		return x, nil
	}
	return DeviceType(0), fmt.Errorf("%s is %w", name, ErrInvalidDeviceType)
}

const (
	// ServerModeDev is a ServerMode of type Dev.
	ServerModeDev ServerMode = iota
	// ServerModeProd is a ServerMode of type Prod.
	ServerModeProd
	// ServerModeTest is a ServerMode of type Test.
	ServerModeTest
)

var ErrInvalidServerMode = errors.New("not a valid ServerMode")

const _ServerModeName = "devprodtest"

var _ServerModeMap = map[ServerMode]string{
	ServerModeDev:  _ServerModeName[0:3],
	ServerModeProd: _ServerModeName[3:7],
	ServerModeTest: _ServerModeName[7:11],
}

// String implements the Stringer interface.
func (x ServerMode) String() string {
	if str, ok := _ServerModeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ServerMode(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ServerMode) IsValid() bool {
	_, ok := _ServerModeMap[x]
	return ok
}

var _ServerModeValue = map[string]ServerMode{
	_ServerModeName[0:3]:  ServerModeDev,
	_ServerModeName[3:7]:  ServerModeProd,
	_ServerModeName[7:11]: ServerModeTest,
}

// ParseServerMode attempts to convert a string to a ServerMode.
func ParseServerMode(name string) (ServerMode, error) {
	if x, ok := _ServerModeValue[name]; ok {
		return x, nil
	}
	return ServerMode(0), fmt.Errorf("%s is %w", name, ErrInvalidServerMode)
}
