// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package enum

import (
	"errors"
	"fmt"
)

const (
	// RoleCodeSuperAdmin is a RoleCode of type super_admin.
	RoleCodeSuperAdmin RoleCode = "super_admin"
	// RoleCodeAdmin is a RoleCode of type admin.
	RoleCodeAdmin RoleCode = "admin"
	// RoleCodeGuest is a RoleCode of type guest.
	RoleCodeGuest RoleCode = "guest"
	// RoleCodeUser is a RoleCode of type user.
	RoleCodeUser RoleCode = "user"
	// RoleCodeUserVip is a RoleCode of type user_vip.
	RoleCodeUserVip RoleCode = "user_vip"
	// RoleCodeUserSvip is a RoleCode of type user_svip.
	RoleCodeUserSvip RoleCode = "user_svip"
)

var ErrInvalidRoleCode = errors.New("not a valid RoleCode")

// String implements the Stringer interface.
func (x RoleCode) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x RoleCode) IsValid() bool {
	_, err := ParseRoleCode(string(x))
	return err == nil
}

var _RoleCodeValue = map[string]RoleCode{
	"super_admin": RoleCodeSuperAdmin,
	"admin":       RoleCodeAdmin,
	"guest":       RoleCodeGuest,
	"user":        RoleCodeUser,
	"user_vip":    RoleCodeUserVip,
	"user_svip":   RoleCodeUserSvip,
}

// ParseRoleCode attempts to convert a string to a RoleCode.
func ParseRoleCode(name string) (RoleCode, error) {
	if x, ok := _RoleCodeValue[name]; ok {
		return x, nil
	}
	return RoleCode(""), fmt.Errorf("%s is %w", name, ErrInvalidRoleCode)
}
